
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5566

feign:
  okhttp:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:4677/raji
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
  
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        
    
message: this is dev env

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1010/eureka
    
